### ISSUE TITLE
Add save command

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/DiscordPlaysPyBoy#15]
A scripted set of button pushes to save the game would be really great.
Other sorts of scripted behavior would also be great, but this is a good first start.

**Comment by I-question-this** [comment]
This will be difficult since the Pokemon Blue menu doesn't start on the same option every time. It instead starts on the last option used.
Additionally, such an action will have to be context aware of what game is being played.

**Comment by DanielRunningen** [comment]
#18 may be able to hold scripted behavior for its games

**Comment by DanielRunningen** [comment]
#18 may be able to hold scripted behavior for its games
