### ISSUE TITLE
Add "shards"

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/DiscordPlaysPyBoy#19]
"shards" are the bots connection to individual servers. I think it would be cool if multiple discord servers are all playing the same game, but that would complicate administration. As such, it should be kept in mind for the "stable alpha" but won't be fully fleshed out until the "first release"

**Comment by DanielRunningen** [comment]
Alternatively, would it be possible for one server to have multiple shards? (Maybe one per designated channel?)

**Comment by I-question-this** [comment]
It would be possible, but that would require a different framework to be built. They can exist simultaneously, but should be separate Git Issues.
