### ISSUE TITLE
Abstract the client to accept different games

### ISSUE THREAD

**Issue by DanielRunningen** [I-question-this/DiscordPlaysPyBoy#8]
Should be controlled by admin which game is being played.

**Comment by I-question-this** [comment]
Because of more options for games other than loading the correct ROM (see #15 ) this is being reopened.
@DanielRunningen used the phrase "Game Library" which inspires something more than just a ROM name and path in the config,py file.

**Comment by I-question-this** [comment]
Also, as @DanielRunningen mentioned in the creation of this issue that #16 is important so that should probably be completed first.

**Comment by DanielRunningen** [comment]
[#18](https://github.com/I-question-this/DiscordPlaysPyBoy/issues/18) ("game library", as mentioned above)
